// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'cell': string;
  'cellDone': string;
  'field': string;
  'horizontalLine': string;
  'horizontalLineBold': string;
  'horizontalLineMarker': string;
  'verticalLine': string;
  'verticalLineBold': string;
  'verticalLineMarker': string;
}
export const cssExports: CssExports;
export default cssExports;
