# Generated by Django 4.2.9 on 2024-02-04 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pattern', '0003_alter_patterncrosstype_pattern_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patterncross',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crosses', to='pattern.patterncrosstype'),
        ),
        migrations.AlterField(
            model_name='patterncrosstype',
            name='pattern',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cross_types', to='pattern.pattern'),
        ),
    ]
